Сделал виджет LastTransaction на экране Home
VitalyPeryatin/1Coin pull request #53
Opened 2022-10-24 16:45 UTC by productomar

![image](https://user-images.githubusercontent.com/99362820/197580487-47b255b1-6101-4607-b1c5-5773ef82efa4.png)

2022-10-24 16:50 UTC, Bittner322 requested changes

2022-10-24 16:50 UTC, Bittner322 commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/home/HomeScreen.kt
> +            .background(AppColors.Purple200)
Ты забыл подтянуть судя по всему изменения в develop. Там уже все другое :(

2022-10-24 16:50 UTC, Bittner322 commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/LastTranscationItem.kt
> +            painter = painterResource(R.drawable.ic_category_1),
Мы уже другим способом получаем картинки, посмотри как это в других местах реализовано

2022-10-24 16:50 UTC, Bittner322 commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/home/HomeScreen.kt
> +            text = stringResource(R.string.main_screen_text),
Мы получаем текст по-другому, посмотри как это сделано на других экранах

2022-10-24 16:51 UTC, Bittner322 commented
У тебя, судя по всему, дублируется ресурс.
/home/runner/work/FinanceTracker/FinanceTracker/android/src/main/res/values/strings.xml: Error: Found item String/home_my_accounts more than one time

2022-10-26 12:06 UTC, VitalyPeryatin requested changes

2022-10-26 12:06 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/LastTranscationItem.kt
> +                    CoinTheme.color.secondaryBackground,
Не забывай про именованные параметры

2022-10-26 12:06 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/LastTranscationItem.kt
> +fun LastTransactionItem(
Думаю, что эта функция может использоваться только на одном экране, поэтому выносить её в CoreUi не надо.

2022-10-26 12:06 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/LastTranscationItem.kt
> +fun LastTransactionItem(
Вынеси функцию `TransactionItem` в CoreUi модуль в отдельном файле из файла `TransactionsScreen`. И переиспользуй уже готовую функцию `TransactionItem`

2022-10-26 12:06 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/LastTransactionHeader.kt
> +fun LastTransactionHeader(modifier: Modifier = Modifier) {
Уже есть функция `MyAccountsHeader`. Переиспользуй её. Надо только переименовать ту функцию и дать возможность передавать в её параметры текст

2022-10-26 12:06 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/LastTransactionWidget.kt
> +fun LastTransactionWidget(modifier: Modifier = Modifier) {
В этот виджет должен приходить параметр `transactions: List<Transaction>`. Если хочется пока замокать данные, то это лучше сделать на уровне репозитория

2022-11-03 01:34 UTC, Bittner322 commented
Актуализируй скриншоты пожалуйста, чтобы посмотреть на итоговый вариант

2022-11-03 05:40 UTC, VitalyPeryatin requested changes

2022-11-03 05:40 UTC, VitalyPeryatin commented on android/build.gradle.kts
> +    implementation(project(mapOf("path" to ":common")))
Эти 2 строки тут не нужны, так как сверху модуль common уже подключен: 
`implementation(projects.common)`

2022-11-03 05:40 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/TitleHeader.kt
> +    textValue: String
Аргументы без дефолтных значений всегда должны быть выше аргументов с дефолтными значениями. Таким образом не надо будет перечислять все параметры при вызове функции, если не используются именованные параметры

2022-11-03 05:40 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/TitleHeader.kt
> +            text = stringResource(textValue),
Для большей переиспользуемости обычно в `TitleHeader` передается уже готовая строка так, чтобы не пришлось вызывать `stringResource()` внутри этой функции. Тогда тот, кто вызывает эту функцию может как напрямую передать строку, так и через `stringResource` использовать идентификатор строки

2022-11-03 05:40 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/LastTransactionWidget.kt
> +fun LastTransactionWidget(modifier: Modifier = Modifier) {
В эту функцию должен передавать `List<Transaction>` и он должен отображаться. Если хочется использовать моковые данные, то их как минимум нужно вынести на уровень вью модели или лучше на уровень репозитория

2022-11-03 06:44 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/TitleHeader.kt
>  import com.finance_tracker.finance_tracker.core.theme.CoinTheme
![telegram-cloud-photo-size-2-5411604530799428255-x](https://user-images.githubusercontent.com/22561563/199661166-4889c6a0-ec9a-45b6-961c-530c95ea96a3.jpg)
![Uploading telegram-cloud-photo-size-2-5411604530799428254-y.jpg…]()

Цифры и обводка не соответствуют дизайну

2022-11-07 17:02 UTC, VitalyPeryatin requested changes

2022-11-07 17:02 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeViewModel.kt
> +    init {
Если функция не возвращает никакие данные, она не может иметь префикс `get...`. В данном случае больше подходит название `loadTransactions()` и разместить эту функцию лучше в `onScreenComposed()`, чтобы при перезаходе на экран подгружать актуальные данные

2022-11-07 17:04 UTC, VitalyPeryatin reviewed
![telegram-cloud-photo-size-2-5425057905968792672-y](https://user-images.githubusercontent.com/22561563/200370834-f42ccb5a-a35b-4072-9337-3a213849753d.jpg)

2022-11-07 17:14 UTC, productomar reviewed
![image](https://user-images.githubusercontent.com/99362820/200372812-93f8eeab-d93a-4779-9e90-6d085483e39e.png)

2022-11-20 19:07 UTC, productomar commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeScreen.kt
> +            CommonTransactionsList(transactions = transactions.takeLast(3))
Не очень понимаю, нужно ли это делать, т.к. у меня в студии (скрин ниже) данная рамка есть

2022-11-20 19:25 UTC, productomar commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/TitleHeader.kt
> +            text = stringResource(text),
Я просмотрел все файлы в `core/ui` и увидел только в `CategoryCard` ту самую переиспользуемость, о которой ты, насколько я понимаю, говоришь, Виталий.

Получается нужно также вынести данный Title в какой-то файл? Пока не очень понимаю, как подтягивать текст, не обращаясь при этом к `stringResources`.

2022-11-27 16:19 UTC, VitalyPeryatin requested changes

2022-11-27 16:19 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/transactions/CommonTransactionList.kt
> +import androidx.compose.foundation.layout.*
wildcards import очень нежелательны. Потом становится неочевидно какой класс из какого пакета, а при росте проекта это становится все более актуально, так как появляется больше похожих классов. 
Тебе нужно изменить настрой студии таким образом, чтобы IDE не добавляла wildcard import. 
wildcart import это импорт со звездочкой

2022-11-27 16:19 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/transactions/CommonTransactionList.kt
> +import java.util.*
wildcart import

2022-11-27 16:19 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeScreen.kt
> +import androidx.compose.runtime.*
wildcard import

2022-11-27 16:19 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeScreen.kt
> +
Пустая строка

2022-11-27 16:19 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeScreen.kt
> +                CommonTransactionsList(
Форматирование поехало. CommonTransactionsList должен быть правее, так как находится внутри блока Box

2022-11-27 16:19 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeScreen.kt
> +                    modifier = Modifier.padding(
Попробуй реализовать обводку вокруг `CommonTransactionsList` без Box. Просто перенеси Modifiers из `Box` в `CommonTransactionsList`. Не факт, что получится, но если получится будет круто. Так было бы логичнее

2022-11-27 17:35 UTC, productomar commented
![image](https://user-images.githubusercontent.com/99362820/204150872-1b7e4adb-b792-4c0f-bdd6-b97d3834473c.png)

2022-12-01 07:50 UTC, closed without merging