FT-70: Modify CI/CD
VitalyPeryatin/1Coin pull request #74
Opened 2022-11-11 11:09 UTC by Bittner322

Модифицировал CI/CD. Создал собсвенный detektAll таск для проверки всех модулей, подредактировал detelt.yml

2022-11-11 16:58 UTC, VitalyPeryatin requested changes

2022-11-11 16:58 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/App.kt
> +import com.google.firebase.crashlytics.ktx.BuildConfig
Кажись лишний импорт попал

2022-11-11 16:58 UTC, VitalyPeryatin commented on build.gradle.kts
> +    //val input = listOf("android/src/main/kotlin", "common/src/androidMain/kotlin", "common/src/commonMain/kotlin", "common/src/desktop/kotlin")
Закомментируемый код - удаляем

2022-11-11 16:58 UTC, VitalyPeryatin commented on build.gradle.kts
> +val detekt by configurations.creating
А не получится ли тут `creating` заменить на `registering` (последний более эффективно выполняет решистрацию таски в Gradle, ускоряя немного сборку)

2022-11-11 16:58 UTC, VitalyPeryatin commented on build.gradle.kts
> +    detekt("io.gitlab.arturbosch.detekt:detekt-cli:1.22.0-RC3")
Если можно, давай все зависимости объявлять в файле `libs.versions.toml`. Если в данном случае иначе нельзя было, то можно и так оставить

2022-11-11 16:58 UTC, VitalyPeryatin commented on build.gradle.kts
> +    repositories {
Мне кажется, что если используется `allprojects`, то `subprojects`, который выше - не нужен. Или наоборот. Не знаю как это работает, если честно, но странно, что сильно дублируются репозитории в одном месте

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Это важное правило, его лучше оставить как было и пофиксить места где оно не соблюдается

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
>        - 'java.util.*'
Список `excludeImports ` я бы оставил пустым. Оно ни к чему тут, думаю

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Тоже важное правило. Давай оставим

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Давай оставим как было это правило

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    maxLineLength: 200
20 символов - слишком длинные строки. Давай оставим как было - 120

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Это важное правило, лучше оставить

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Давай оставим это правило

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Давай оставим это правило

2022-11-11 16:58 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Давай оставим это правило

2022-11-12 08:49 UTC, Bittner322 commented on build.gradle.kts
> +    detekt("io.gitlab.arturbosch.detekt:detekt-cli:1.22.0-RC3")
по другому не получается

2022-11-12 08:50 UTC, Bittner322 commented on build.gradle.kts
> +val detekt by configurations.creating
Не получается

2022-11-12 08:51 UTC, Bittner322 commented on build.gradle.kts
> +    repositories {
Убрал `subprojects`

2022-11-12 08:59 UTC, Bittner322 commented on config/detekt/detekt.yml
> +    active: false
вернул правило и поправил косяки, связанные с ним

2022-11-12 12:22 UTC, VitalyPeryatin requested changes

2022-11-12 12:22 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/DragDropExt.kt
> +val LazyListItemInfo.OffsetEnd: Int
Это property должны начинаться с маленькой буквы. Если получится - лучше отдельно для них прописать exclude. Если нет, то придется отключать правило детекта

2022-11-13 11:25 UTC, VitalyPeryatin approved these changes

2022-11-13 11:25 UTC, merged